### ISSUE TITLE
Add register activity

### ISSUE THREAD

**Issue by acool294** [acool294/ZeroBeg#1]
There should be a button in the map activity. when we click on that button it will switch to register activity
Register activity should have the following feature:

- Capture Picture
- Select the superpower
-> Visual Disabilities
-> Hearing Disabilities
-> Mental Disabilities
-> Physical Disabilities
- Comments
Submit

**Comment by negiabhisek** [comment]
Going to add a feature for choosing to whether to upload or capture images.

Till now basic UI is developed. Better UI and additional options can be added in future.

**Comment by negiabhisek** [comment]
Currently the code is frontend and view only. We need to add database connectivity i future.
